### ISSUE TITLE
ORCID integration

### ISSUE THREAD

**Issue by ceteri** [Coleridge-Initiative/RCApi#25]
Integrate with the public API for ORCID.
This requires an API access token, which is available to ORCID members.

 - <https://orcid.org/developer-tools>
 - <https://pub.orcid.org/v2.0/>
 - <https://support.orcid.org/hc/en-us/articles/360006897174>

**Comment by lobodemonte** [comment]
Most of ORCID's API calls require you know the orcid of the author you're looking up but once you figure that out, the API is useful for fetching works/funding/employment related to the author

Public API: https://pub.orcid.org/v3.0/#/
Sample page: https://orcid.org/0000-0002-8139-2960

@ceteri, are the other uses I might have missed from this API?

**Comment by ceteri** [comment]
Thank you @lobodemonte, we'll have ORCIDs for many of the authors. It's our main *persistent identifier* in the graph for people.

One of the goals of this is to support adding another entity into the graph, for author **affiliations**. Using the `/v2.0/{orcid}/employments` should help with that.  Also the `/v2.0/{orcid}/works` endpoint can help us find additional publications to use with the ML model, since authors will commonly do repeated work with a set of datasets over a period of time.

It's possible that funding information will become important later, although we haven't identified it yet.

**Comment by lobodemonte** [comment]
In that case I'll add ORCID functions to 
1. Find publications by ORCID
2. Find author affiliations by ORCID 
3. Find related funding (if time permits)

**Comment by ceteri** [comment]
Great, thanks!
