### ISSUE TITLE
KG errors during Step 2

### ISSUE THREAD

**Issue by ceteri** [Coleridge-Initiative/RCApi#27]
The following errors during Step 2 (title search) in the KG workflow. Looks like some title includes both colon `:` and double quote `"` characters, and that causes problems. Is it for Dimensions?

```
20191206_ncses_publications.js:  15%|########1                                              | 18/121 [01:12<06:35,  3.84s/it]2 QuerySyntaxErrors found
2 LexerErrors found
  * [Line 1:32] (': Identifying and Responding to the Need for New Academic Leadership"') token recognition error at: ':'
  * [Line 1:100] ('"') token recognition error at: '"'
```

**Comment by ceteri** [comment]
Also,

```
20191119_ArizonaTemporaryAssis:  67%|######################################6                   | 2/3 [00:08<00:04,  4.71s/it]1 QuerySyntaxError found
1 LexerError found
  * [Line 1:81] ('"') token recognition error at: '"'
```

**Comment by ceteri** [comment]
Also, 

```
20191119_FloridaWAGES_publicat:  75%|##########################################              | 15/20 [00:48<00:15,  3.10s/it]2 QuerySyntaxErrors found
2 LexerErrors found
  * [Line 1:12] (', Globalisierung und Sozialpolitik"') token recognition error at: ','
  * [Line 1:46] ('"') token recognition error at: '"'
```

**Comment by ceteri** [comment]
Also,

```
20190717_usda_wic_publications:  21%|###########5                                          | 132/615 [07:10<34:59,  4.35s/it]2 QuerySyntaxErrors found
2 LexerErrors found
  * [Line 1:8] (''LOVING SUPPORT' TO BUILD A BREASTFEEDING FRIENDLY COMMUNITY" PROJECT BRINGS TOGETHER THE WIC PROGRAM AND COMMUNITY PARTNERS TO ADDRESS BARRIERS"') token recognition error at: '''
  * [Line 1:23] ('' TO BUILD A BREASTFEEDING FRIENDLY COMMUNITY" PROJECT BRINGS TOGETHER THE WIC PROGRAM AND COMMUNITY PARTNERS TO ADDRESS BARRIERS"') token recognition error at: '''
20190717_usda_wic_publications:  32%|#################3                                    | 198/615 [11:27<32:08,  4.62s/it]1 QuerySyntaxError found
1 LexerError found
  * [Line 1:34] ('," A BREASTFEEDING PROMOTION PROJECT IN THE SPECIAL SUPPLEMENTAL NUTRITION PROGRAM FOR WOMEN, INFANTS AND CHILDREN (WIC)"') token recognition error at: ','
```

**Comment by srand525** [comment]
> The following errors during Step 2 (title search) in the KG workflow. Looks like some title includes both colon `:` and double quote `"` characters, and that causes problems. Is it for Dimensions?
> 
> ```
> 20191206_ncses_publications.js:  15%|########1                                              | 18/121 [01:12<06:35,  3.84s/it]2 QuerySyntaxErrors found
> 2 LexerErrors found
>   * [Line 1:32] (': Identifying and Responding to the Need for New Academic Leadership"') token recognition error at: ':'
>   * [Line 1:100] ('"') token recognition error at: '"'
> ```

Title was `"BPD Emerging Leaders 2010a\"2016: Identifying and Responding to the Need for New Academic Leadership"` where the `a\"` is supposed to be an em dash - now rectified in the original CSV and JSON, but worth noting that in your error, the title was truncated (near, but not right after, the encoding issue)

**Comment by srand525** [comment]
> Also,
> 
> ```
> 20191119_FloridaWAGES_publicat:  75%|##########################################              | 15/20 [00:48<00:15,  3.10s/it]2 QuerySyntaxErrors found
> 2 LexerErrors found
>   * [Line 1:12] (', Globalisierung und Sozialpolitik"') token recognition error at: ','
>   * [Line 1:46] ('"') token recognition error at: '"'
> ```

Original title here was `"New Labour", Globalisierung und Sozialpolitik` and I changed it to 
`'New Labour', Globalisierung und Sozialpolitik` in the original csv. In a PR on the CSV=>JSON template, I added a line to `scrub_unicode` to replace double-quotes in a title to single quotes. Will this cause issues downstream, or is it an acceptable substitution?

**Comment by srand525** [comment]
> Also,
> 
> ```
> 20190717_usda_wic_publications:  21%|###########5                                          | 132/615 [07:10<34:59,  4.35s/it]2 QuerySyntaxErrors found
> 2 LexerErrors found
>   * [Line 1:8] (''LOVING SUPPORT' TO BUILD A BREASTFEEDING FRIENDLY COMMUNITY" PROJECT BRINGS TOGETHER THE WIC PROGRAM AND COMMUNITY PARTNERS TO ADDRESS BARRIERS"') token recognition error at: '''
>   * [Line 1:23] ('' TO BUILD A BREASTFEEDING FRIENDLY COMMUNITY" PROJECT BRINGS TOGETHER THE WIC PROGRAM AND COMMUNITY PARTNERS TO ADDRESS BARRIERS"') token recognition error at: '''
> 20190717_usda_wic_publications:  32%|#################3                                    | 198/615 [11:27<32:08,  4.62s/it]1 QuerySyntaxError found
> 1 LexerError found
>   * [Line 1:34] ('," A BREASTFEEDING PROMOTION PROJECT IN THE SPECIAL SUPPLEMENTAL NUTRITION PROGRAM FOR WOMEN, INFANTS AND CHILDREN (WIC)"') token recognition error at: ','
> ```

In the first, there are both single and double quotes within the title, see: https://www.sciencedirect.com/science/article/pii/S0002822308701615?via%3Dihub

**Comment by ceteri** [comment]
Thanks for fixing those errors in the publication partitions.

Even so, the API needs to handle these kinds of errors better -- it shows during a full run on the workflow. I'll fix that aspect here.
