### ISSUE TITLE
CORE API integration

### ISSUE THREAD

**Issue by ceteri** [Coleridge-Initiative/RCApi#34]
Integrating <https://core.ac.uk/> API access, see:
- <https://github.com/oacore/pyoacore>
- <https://github.com/oacore/or2016-api-demo/blob/master/OR2016%20API%20demo.ipynb>

This could be used for:
- finding open access PDFs
- DOI lookup
- ISSN lookup
- identifying similar articles (expanding the KG)

**Comment by lobodemonte** [comment]
Hey Paco, do we want to use the API URL directly or the python package pyocore? or a combo of them two?

**Comment by ceteri** [comment]
The `pyoacore` library should probably help. I took a quick look through and it's based on Swagger/OpenAPI.  Seems to be used a lot.

If there are features in the API which can't be reached through the library, then we could go directly to the API URL

**Comment by ceteri** [comment]
implemented by #51
