### ISSUE TITLE
NSF PAR integration

### ISSUE THREAD

**Issue by ceteri** [Coleridge-Initiative/RCApi#43]
Integrate with the PAR search at NSF, which is adding more metadata about dataset <=> publication links:

 - <https://par.nsf.gov/search/term:nhanes>

**Comment by lobodemonte** [comment]
Per their HelpDesk team, there's no API for this page so we will have to use BeautifulSoup and learn from their Advanced Search how to format the URL for the searches we need to do

**Comment by ceteri** [comment]
Thanks for getting into contact with their HelpDeck.

I can see the source for the Advanced Search form:
```
<form action="" id="index_search" class="adv_search" method="POST" autocomplete="off">
```
and for its `Find` submit button.

There's no action defined for the form, and no apparent JavaScript run on form events.  I see at the bottom of the HTML page where the JavaScript `$(document).ready(function () {...` runs to set up the query input.  Perhaps some of the other JavaScript that's loaded is manipulating the form?

**Comment by lobodemonte** [comment]
I was thinking that maybe instead of parsing the html, that we could download the CSV (option on the webpage) and transform that to a JSON since the CSV has a lot more rich information on each publication than what's presented on the search page

**Comment by ceteri** [comment]
Good approach! Hope that works well.
