### ISSUE TITLE
full-text search order for Dimensions

### ISSUE THREAD

**Issue by ceteri** [Coleridge-Initiative/RCApi#60]
from @ernestogimeno:
> not sure also id there is an issue from our side or just how Dimensions works:
> The full text search of "Agricultural Resource Management Survey USDA" returns 1 hit. But searching "USDA Agricultural Resource Management Survey" returns 78 hits.

**Comment by lobodemonte** [comment]
It doesn't look like an issue on our side. 
I've sent an email to Dimensions Support Team to find out how the search_term is being used and why the order of words is having such a big impact

**Comment by lobodemonte** [comment]
I got the following response from Dimensions Support: 
> As you're doing a phrasal search using quotation marks the word order has to match, so that's what makes the difference here.
So basically when doing exact_match using dimensions API, the order of words matters 

@ernestogimeno hope that helps

**Comment by lobodemonte** [comment]
@ernestogimeno I don't think you can make specific parts of a search mandatory while other parts being optional, it's either all of it exact or not
