### ISSUE TITLE
DataCite full_text_search returns too much results

### ISSUE THREAD

**Issue by ernestogimeno** [Coleridge-Initiative/RCApi#62]
Using federated_search.py script (from RCGraph repo) I noticed that DataCite always returns the 'limit' number of results, where others APIs return a different range of results depending on how broad the search terms are.
 
For example:
```
Search terms "Survey of Doctorate Recipients"
limit 400

Crossref returned 5 hits
OpenAIRE returned 20 hits
PubMed returned 5 hits
Dimensions returned 335 hits
DataCite returned 400 hits

```

I don't know if this is a bug or not. But for the use case of generating a datadrop, could be a bad thing.

**Comment by lobodemonte** [comment]
Checking

**Comment by lobodemonte** [comment]
@ernestogimeno , this does not seem to be a bug 
Per the Datacite docs:

> By default up to 25 records are returned at a time, this can be changed using the page[size] query parameter (allowed values in range 0-1000) https://support.datacite.org/docs/pagination

Although I did see a drop in matches if exact_match = True instead of False

**Comment by ernestogimeno** [comment]
Thanks!.

So, it is not something on our side. I was not using DataCite results in the federated_search script since I don't have yet a parser for that. But we should keep this present when we start using this API integration in that script.
