### ISSUE TITLE
Article search problem

### ISSUE THREAD

**Issue by happylilem** [Coleridge-Initiative/RCApi#77]
Hi, I'm trying to use this library to obtain PubMed article attributes. The sample script works perfectly when I used it to search for the sample PubMed article “Deal or no deal? ”. However, when I tried to substitute this article with other PubMed articles, my Jupyter Notebook simply responded "None" instead of any results as it did for the sample article. I wonder if there were any restrictions on the articles that could be reached by this library. I would be very thankful if you could help me with this!

**Comment by happylilem** [comment]
The search string that worked is:
`title = "Deal or no deal? The prevalence and nutritional quality of price promotions among U.S. food and beverage purchases."`
and it returns the article attributes as 
`OrderedDict([('doi', '10.1016/j.appet.2017.07.006'), ('title', 'Deal or no deal? The prevalence and nutritional quality of price promotions among U.S. food and beverage purchases'), ('url', 'https://europepmc.org/articles/PMC5574185/'), ('authors', ['Taillie, Lindsey Smith', 'Ng, Shu Wen', 'Xue, Ya', 'Harding, Matthew']), ('open', True)])`

When I changed the string to another PubMed article such as this one:
`title = "A Comparative Study of Free Oligosaccharides in the Milk of Domestic Animals"`
The response is `None`.
I tried several other articles, and the responses were also `None`. The article titles didn't contain any special characters.

**Comment by happylilem** [comment]
Here is the entire script I used:
`from richcontext import scholapi as rc_scholapi`
`schol = rc_scholapi.ScholInfraAPI(config_file="rc.cfg", logger=None)`
`source = schol.openaire`
`title = "Deal or no deal? The prevalence and nutritional quality of price promotions among U.S. food and beverage purchases."`
`if source.has_credentials():`
`    response = source.title_search(title)`
`    if response.message:`
`        print(response.message)`
`    else:`
`        print(response.meta)`

**Comment by ernestogimeno** [comment]
Hi @happylilem, 

I tested your code and I see that you are using OpenAIRE integration, instead of the intended PubMed, so if you do this on your code...

`source = schol.pubmed`

... you will get a result. 

I realized we need to improve our documentation to make more explicit how to access each service. For now, you can see [here](https://github.com/Coleridge-Initiative/RCApi/blob/master/richcontext/scholapi/scholapi.py#L1724 ) a hint of the other options you have.
